### ISSUE TITLE
【Proposal】 Abolish automatic execution of E2E tests on push to 'feature/xxxx' branches

### ISSUE THREAD

**Issue by yu-smc** [t29mato/starry-digitizer#101]
@t29mato 
(not urgent at all)
I propose modification as stated in the title to avoid reaching Cypress's monthly limit of test execution.

Basically we can run cypress locally when necessary, so I assume it is enough that the automatic E2E tests run only when pushing to develop branch.

**Comment by t29mato** [comment]
@yu-smc 
Thank you for your suggestion. I understand the idea, but I'm concerned about relying on individuals for Cypress local execution. It may work for you, but I'm worried whether future collaborators on StarryDigitizer will consistently remember to run Cypress locally. Also, I'm unsure if we'll remember to do this a year from now.

**Comment by t29mato** [comment]
> What happens when you meet your test results limit?
> Tests will continue to run but parallelization will be disabled and run data will be hidden from Cypress Cloud until the plan is upgraded or the next usage period begins.

quoted from a email by cypress team

Currently, even if we exceed the limit, it only results in the suspension of parallelization or the inability to view details.
So, I think neither has any impact on our development.

**Comment by yu-smc** [comment]
@t29mato 
> Even if we exceed the limit, it only results in the suspension of parallelization or the inability to view details.
So, neither has any impact on our development.

I'm just not sure what will happen if the test failed when exceeding cypress limits: can we still check the error log? ('inability to view details' means another thing?)

**Comment by t29mato** [comment]
@yu-smc 
I believe we may not be able to see the details of the test on Cypress cloud, but it is clear that the code has failed the test, and the details should be verifiable if executed locally. I think the most critical situation to avoid is releasing with the regression still present.

**Comment by yu-smc** [comment]
> I think the most critical situation to avoid is releasing with the regression still present.
In terms of above, I thought I would notice the same problem now because the test would fail when merging into the develop branch, but I understood your point :)

Let's operate it as is and see how it goes.

**Comment by t29mato** [comment]
I'm sorry; I forgot to mention in my comments that we should only stop the feature branch. I retract what I said. It will be a good idea to discontinue Cypress E2E tests on the feature branch only.
I agree with your suggestion.

**Comment by yu-smc** [comment]
Removed E2E test CI from the preview build: https://github.com/t29mato/starry-digitizer/pull/128
