### ISSUE TITLE
Set the coordinate axis setting to 2 points instead of 4 points

### ISSUE THREAD

**Issue by t29mato** [t29mato/starry-digitizer#11]
> Since most graphs have little or no tilt on the coordinate axes, why not set the coordinate axes by extending the crosshair cursor wide and specifying two points, as shown in the figure below?
> Currently, you have to click on 4 points, 2 on the x-axis and 2 on the y-axis, and then use the arrow keys to fine-tune, but you will only need 2 points.
> <img width="457" alt="image" src="https://github.com/t29mato/starry-digitizer/assets/30012556/701ab608-2208-4bda-ab8e-db74b79a6d84">

by Starrydata team

## As-is
<img width="736" alt="image" src="https://github.com/t29mato/starry-digitizer/assets/30012556/1ae0f8e7-2ff2-4604-bb9a-06ffa39a7047">

**Comment by yu-smc** [comment]
実装済みの機能につきcloseします
