### ISSUE TITLE
In the definition mode with 4 points of XY axis, when the tilt is set to ON, the values are incorrect when X1 and Y1 are different coordinates.

### ISSUE THREAD

**Issue by t29mato** [t29mato/starry-digitizer#17]
### Description

The extracted value in the [degitizer確認２.pptx](https://github.com/t29mato/starry-digitizer/files/12115608/degitizer.pptx) file is incorrect.

### Steps to Reproduce

1. Check the `Consider graph tilt` option.
2. Set the x1 and y1 coordinates with different positions.

### Expected Behavior

The extracted value should be accurate based on the correct calculation formula.

### Actual Behavior

The value extracted is incorrect due to a typo in the code.

**Comment by yu-smc** [comment]
解消済みのためcloseします
