### ISSUE TITLE
Relate 'isLog' to a figure instead of XY axis set?

### ISSUE THREAD

**Issue by yu-smc** [t29mato/starry-digitizer#213]
Currently, the flag 'isLog', which indicates whether the plot is on a linear or logarithmic scale, is associated with each set of axes. This allows users to collect data with different scales (e.g., linear scale on the first axis set and logarithmic scale on the second axis set).

However, I think the scale for each X and Y axis should be associated with the figure as a whole, not with individual axis sets.

Additionally, when considering integration with Starrydata3, there may be discrepancies in the data, as we plan to associate the scale with the entire figure.

The key question is whether there could ever be different scales within a single figure. My assumption is that there wouldn't be. If there were, users could simply treat the data as belonging to separate figures, right?

To clarify, I am thinking of relating both xIsLog and yIsLog with a figure domain which have to be newly created.

What do you think? @t29mato 
(we can also discuss in our team MTG)

**Comment by t29mato** [comment]
In Starrydata3, each Figure corresponds to one XY axis. Therefore, when integrating StarryDigitizer with Starrydata3, the functionality for multiple XY axes will need to be turned off. 
So, the user needs to change the figure when 1 figure has multiple xy axes.
