### ISSUE TITLE
Exclude version information from being displayed except in the production environment.

### ISSUE THREAD

**Issue by t29mato** [t29mato/starry-digitizer#91]
## Motivation

In the development environment and other preview environments created by Vercel, the old build number remains visible, causing confusion.

<img width="1696" alt="Screenshot 2023-12-25 at 18 02 39" src="https://github.com/t29mato/starry-digitizer/assets/30012556/9b26013e-bcd5-4f6a-9418-574d81cb1fb9">

## To-be

Exclude version information from being displayed except in the production environment
(Production environment means github-workflow's production deployment)

**Comment by t29mato** [comment]
@yu-smc 
余裕あれば、よろしくお願いします 🙇

**Comment by yu-smc** [comment]
Solved in [v1.2.0](https://github.com/t29mato/starry-digitizer/releases/tag/v1.2.0)
